name: Genstats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: cicirello/user-statistician@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          colors: onedark
          image-file: stats.svg
          fail-on-error: true
