name: Gen metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SPSTVMCR
          template: classic
          filename: metrics.svg
          base: header, activity, repositories
          config_timezone: Etc/UTC

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: percentage
          plugin_languages_limit: 12

          plugin_topics: yes
          plugin_topics_limit: 12

          plugin_habits: yes
          plugin_habits_facts: yes
          
          
      - name: Commit metrics.svg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add metrics.svg
            git commit -m "chore: update metrics.svg"
            git push
          else
            echo "No changes to commit."
          fi
